services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - charity-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd123!
      - POSTGRES_DB=charitysale
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - charity-network

networks:
  charity-network:
    driver: bridge

volumes:
  postgres_data: